---
# handlers file for osconfig

- name: Restart systemd-logind
  systemd:
    name: systemd-logind
    state: restarted


- name: Start KVM service
  ansible.builtin.systemd:
    name: libvirtd
    enabled: true
    state: started
