---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: ubuntu:24.04
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../../roles
verifier:
  name: ansible
