---
# tasks file for jupyterhub

# TODO
# set up cronjob to rebuild/pull images regularly
# use variables

- name: install prequesites
  apt:
    pkg: 
      - git
      - docker.io
      - docker-compose-v2
      - docker-buildx
      - python3-requests
    state: present
    update_cache: yes


- name: clone jupyterhub repository
  git:
    repo: https://github.com/zr123/jupyterhub
    dest: /opt/jupyterhub/


- name: pully scipy image
  community.docker.docker_image_pull:
    name: jupyter/scipy-notebook:latest


- name: build tensorflow image
  community.docker.docker_image_build:
    path: /opt/jupyterhub
    name: tensorflow-jupyterhub


- name: start jupyterhub
  community.docker.docker_compose_v2:
    project_src: /opt/jupyterhub
