---
# tasks file for jupyterhub

- name: install prequesites
  apt:
    pkg: 
      - git
      - docker.io
      - docker-compose-v2
      - docker-buildx
      - python3-requests
      - anacron
    state: present
    update_cache: yes


- name: clone jupyterhub repository
  git:
    repo: "{{ jupyterhub_repo }}"
    dest: "{{ install_path }}"


- name: setup jupyterhub cronjob for setup & update
  template:
    src: jupyterhub_cron.sh.j2
    dest: /etc/cron.monthly/jupyterhub_cron.sh
    mode: '0755'


- name: run jupyterhub cronjob for initial setup
  command:
    cmd: /etc/cron.monthly/jupyterhub_cron.sh
  changed_when: false
