---
# tasks file for osconfig

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes


- name: install prequesites
  apt:
    pkg: 
      - curl
      - gpg
      - python3-requests
      - wget
    state: present
    update_cache: yes


- name: Add Nvidia gpgkey
  apt_key:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    state: present


- name: Add Nvidia apt repo
  get_url:
    url: https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list
    dest: /etc/apt/sources.list.d/nvidia-container-toolkit.list
 

- name: Install required packages
  apt:
    pkg: 
      - docker.io
      - nvidia-container-toolkit
    state: present
    update_cache: yes


- name: disable lock screen
  command: 
    cmd: "gsettings set org.gnome.desktop.lockdown disable-lock-screen 'true'"
  tags: molecule-notest


- name: create luks password file
  copy:
    content: "{{ encryption_key }}"
    dest: "{{ password_file }}"
  no_log: yes


- name: create crypttab entries for drives
  community.general.crypttab:
    name: "{{ item.name }}"
    backing_device: "{{ item.device }}"
    password: "{{ password_file }}"
    opts: luks
    state: present
  loop: "{{ disks }}"


- name: create fstab entries for drives
  mount:
    path: "{{ mount_path + item.name }}"
    src: "{{ '/dev/mapper/' + item.name }}"
    state: present
    fstype: ext4
  loop: "{{ disks }}"


# see https://docs.portainer.io/advanced/cli
- name: set up portainer volume
  community.docker.docker_volume:
    name: portainer_data


- name: set up portainer
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:lts
    command: --admin-password='{{ portainer_password }}'
    restart_policy: always
    ports:
      - 9443:9443
      # - 8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data


# todo set up portainer config
# - name:
