---
# tasks file for osconfig

- name: Update system and install apt packages
  block:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
    notify: Autoinstall recommended ubuntu-drivers

  - name: install packages
    apt:
      pkg: 
        - curl
        - gpg
        - wget
        - flatpak
      #  - gnome-software-plugin-flatpak
        - kde-config-flatpak
        - xdg-desktop-portal-kde
      state: present
      update_cache: yes


- name: Setup flathub and install flatpaks
  block:
  - name: Add the flathub flatpak repository
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

  - name: Install flatpaks
    community.general.flatpak:
      name:
        - com.heroicgameslauncher.hgl
        # - dev.lizardbyte.app.Sunshine
        # install Sunshine manually instead: see https://docs.lizardbyte.dev/projects/sunshine/latest/md_docs_2getting__started.html
        # download from https://github.com/LizardByte/Sunshine/releases/latest
        # install with sudo dpkg -i ./sunshine-{distro}-{distro-version}-{arch}.deb
        # setup start on boot with: systemctl --user --now enable app-dev.lizardbyte.app.Sunshine


- name: Configure Nvidia support for containers
  block:
  - name: Add Nvidia gpgkey
    apt_key:
      url: https://nvidia.github.io/libnvidia-container/gpgkey
      state: present

  - name: Add Nvidia apt repo
    get_url:
      url: https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list
      dest: /etc/apt/sources.list.d/nvidia-container-toolkit.list

  - name: Install nvidia package
    apt:
      pkg: 
        - nvidia-container-toolkit
      state: present
      update_cache: yes


- name: Setup for additional encrypted disk(s)
  block:
  - name: create luks password file
    copy:
      content: "{{ encryption_key }}"
      dest: "{{ password_file }}"
    no_log: yes

  - name: create crypttab entries for drives
    community.general.crypttab:
      name: "{{ item.name }}"
      backing_device: "{{ item.device }}"
      password: "{{ password_file }}"
      opts: luks
      state: present
    loop: "{{ disks }}"

  - name: create fstab entries for drives
    mount:
      path: "{{ mount_path + item.name }}"
      src: "{{ '/dev/mapper/' + item.name }}"
      state: present
      fstype: ext4
    loop: "{{ disks }}"


- name: Setup QEMU/KVM
  block:
  - name: install packages
    apt:
      pkg:
        - qemu-kvm
        - libvirt-daemon-system
        - libvirt-clients
        - bridge-utils 
        - virt-manager
        - virtinst 
        - ovmf
      state: present
      update_cache: yes

  - name: Grant VM permissions
    ansible.builtin.user:
      name: "{{ user }}"
      groups: libvirt,kvm
      append: true
    notify: Start KVM service

  - name: Verify KVM acceleration is available
    ansible.builtin.command: kvm-ok
    register: kvm_check
    changed_when: false
    failed_when: "'KVM acceleration can be used' not in kvm_check.stdout"

  - name: Show kvm-ok result
    ansible.builtin.debug:
      var: kvm_check.stdout


- name: Add multiverse repository
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: false
  loop:
    - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} multiverse"
    - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates multiverse"


- name: Install Steam-installer
  ansible.builtin.apt:
    name: steam-installer
    state: present
    update_cache: yes
