---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian
    image: debian:11
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
verifier:
  name: ansible
