# This workflow will install ansible and molecule and will tests the ansible roles

name: Molecule

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-wol:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libssl-dev
        python -m pip install --upgrade pip
        pip install molecule ansible molecule-plugins[docker]

    - name: Test wol role individually
      working-directory: ./roles/wol
      run: molecule test


  test-dropbear:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libssl-dev
        python -m pip install --upgrade pip
        pip install molecule ansible molecule-plugins[docker]

    - name: Test dropbear role individually
      working-directory: ./roles/dropbear
      run: molecule test


  test-osconfig:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libssl-dev
        python -m pip install --upgrade pip
        pip install molecule ansible molecule-plugins[docker]
    - name: Test osconfig role individually
      working-directory: ./roles/osconfig
      run: molecule test


  test-playbook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libssl-dev
        python -m pip install --upgrade pip
        pip install molecule ansible molecule-plugins[docker]
    - name: Test main.yml playbook
      run: molecule test
